## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file Prvi_dio_sagetex.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100); _sage_const_22 = Integer(22); _sage_const_36 = Integer(36); _sage_const_35 = Integer(35); _sage_const_27 = Integer(27); _sage_const_25 = Integer(25)## This file (Prvi_dio_sagetex.sagetex.sage) was *autogenerated* from Prvi_dio_sagetex.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('Prvi_dio_sagetex', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
             preostaleKarte = _sage_const_36 
except:
 _st_.goboom(_sage_const_22 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex((_sage_const_1  - (_sage_const_0 /preostaleKarte))*_sage_const_100 ))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.inline(_sage_const_1 , latex( RR((_sage_const_1 -(_sage_const_2 /preostaleKarte))*_sage_const_100 ) ))
except:
 _st_.goboom(_sage_const_27 )
try:
 _st_.commandline(_sage_const_0 , r"""
            sage: brojJacihIstaBoja = 2
            sage: brojJacihBriskula = 10 - 1 - 1
            sage: vjerojatnost = 1 - (brojJacihIstaBoja + brojJacihBriskula)/preostaleKarte
            sage: RR(vjerojatnost*100)
        
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_35 )
_st_.endofdoc()
